/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 批量上传视频 */
        post: operations["uploadVideos"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 开始批量处理
         * @description 创建异步批次；前端使用返回的批次 ID 轮询处理进度。
         */
        post: operations["createBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询批次进度和结果 */
        get: operations["getBatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 下载处理后的视频 */
        get: operations["downloadArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /**
             * @description 稳定的机器可读错误码。
             * @example INVALID_REQUEST
             * @example FILE_TOO_LARGE
             * @example PROCESSING_FAILED
             */
            code: string;
            /** @description 可直接展示或记录的错误说明。 */
            message: string;
        };
        Upload: {
            /** Format: uuid */
            id: string;
            file_name: string;
            /** Format: int64 */
            size_bytes: number;
        };
        UploadsResponse: {
            uploads: components["schemas"]["Upload"][];
        };
        BatchCreateRequest: {
            upload_ids: string[];
            /** @description 服务端可写的导出目录；服务端必须校验并限制允许的路径范围。 */
            output_directory: string;
            /**
             * @description 同时处理的视频数量；接口不设置上限，请调用方按机器资源合理填写。
             * @default 1
             */
            concurrency: number;
            narration?: components["schemas"]["NarrationOptions"];
            deduplication?: components["schemas"]["DeduplicationOptions"];
        };
        NarrationOptions: {
            /**
             * @description 开启后由服务端完成视频分析、文案生成、TTS、字幕和音视频合成。
             * @default false
             */
            enabled: boolean;
            /**
             * @description 解说语言或口音，例如 zh-CN、zh-TW。
             * @default zh-CN
             */
            language: string;
            /** @description 可选音色；不传时使用服务端默认音色。 */
            voice_id?: string;
            /** @description 可选的语气描述。 */
            voice_prompt?: string;
        };
        DeduplicationOptions: {
            /**
             * @description 改变输出文件的二进制摘要。
             * @default true
             */
            change_file_hash: boolean;
            /** @default true */
            reencode: boolean;
            /**
             * @description 随机微调亮度、对比度、饱和度并添加轻微噪点。
             * @default false
             */
            color_noise_tweak: boolean;
            /**
             * @description asset 从 resource/borders 随机选择透明 PNG 覆盖到原画布，不改变输出宽高比。
             * @default none
             * @enum {string}
             */
            border_mode: "none" | "blurred" | "solid" | "asset";
            /** @default false */
            sticker: boolean;
            /** @default false */
            subtitle_mask: boolean;
            /**
             * @description 随机轻微裁剪或缩放。
             * @default false
             */
            crop_scale: boolean;
            /**
             * @description 随机决定是否水平镜像。
             * @default false
             */
            mirror: boolean;
            /**
             * @description 在服务端安全范围内随机微调视频和音频速度。
             * @default false
             */
            speed_tweak: boolean;
        };
        /** @enum {string} */
        BatchStatus: "queued" | "processing" | "succeeded" | "partially_succeeded" | "failed";
        /** @enum {string} */
        JobStatus: "queued" | "processing" | "succeeded" | "failed";
        /** @enum {string} */
        JobStage: "queued" | "analyzing" | "synthesizing" | "processing" | "completed";
        VideoJob: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            upload_id: string;
            file_name: string;
            status: components["schemas"]["JobStatus"];
            stage: components["schemas"]["JobStage"];
            progress: number;
            /** @description 前端状态提示，例如“处理中”或“处理成功了”。 */
            message?: string;
            /** @description 成功后的视频保存路径。 */
            output_path?: string;
            /**
             * Format: uuid
             * @description 成功后用于下载视频的产物 ID。
             */
            artifact_id?: string;
            error?: components["schemas"]["Error"] | null;
        };
        Batch: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["BatchStatus"];
            /** @description 整个批次的百分比进度。 */
            progress: number;
            total: number;
            succeeded: number;
            failed: number;
            jobs: components["schemas"]["VideoJob"][];
        };
        BatchResponse: {
            batch: components["schemas"]["Batch"];
        };
    };
    responses: {
        /** @description 请求失败 */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        BatchId: string;
        ArtifactId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务可用 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
    uploadVideos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @description 支持服务端配置允许的格式，例如 MP4、MOV。 */
                    files: string[];
                };
            };
        };
        responses: {
            /** @description 上传成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadsResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            413: components["responses"]["ErrorResponse"];
        };
    };
    createBatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "upload_ids": [
                 *         "7299805d-e188-481e-9ef4-f6915af55bd0",
                 *         "9fbfcd61-9519-4513-b234-8ff483e452b3"
                 *       ],
                 *       "output_directory": "./storage/outputs",
                 *       "concurrency": 2,
                 *       "narration": {
                 *         "enabled": true,
                 *         "language": "zh-TW",
                 *         "voice_prompt": "成熟、克制、略带悬疑感"
                 *       },
                 *       "deduplication": {
                 *         "change_file_hash": true,
                 *         "reencode": true,
                 *         "color_noise_tweak": true,
                 *         "border_mode": "blurred",
                 *         "sticker": false,
                 *         "subtitle_mask": true,
                 *         "crop_scale": true,
                 *         "mirror": false,
                 *         "speed_tweak": true
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["BatchCreateRequest"];
            };
        };
        responses: {
            /** @description 批次已创建 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            429: components["responses"]["ErrorResponse"];
        };
    };
    getBatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: components["parameters"]["BatchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 批次状态；建议处理期间每 1 至 2 秒轮询一次。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResponse"];
                };
            };
            404: components["responses"]["ErrorResponse"];
        };
    };
    downloadArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 视频文件 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "video/mp4": string;
                    "application/octet-stream": string;
                };
            };
            404: components["responses"]["ErrorResponse"];
        };
    };
}
